/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Size } from "./types/sizes.type";
import { Color } from "./types/color.type";
export namespace Components {
    interface TeraButton {
        "color": Color;
        "rounded": boolean;
        "size": Size;
    }
}
declare global {
    interface HTMLTeraButtonElement extends Components.TeraButton, HTMLStencilElement {
    }
    var HTMLTeraButtonElement: {
        prototype: HTMLTeraButtonElement;
        new (): HTMLTeraButtonElement;
    };
    interface HTMLElementTagNameMap {
        "tera-button": HTMLTeraButtonElement;
    }
}
declare namespace LocalJSX {
    interface TeraButton {
        "color"?: Color;
        "rounded"?: boolean;
        "size"?: Size;
    }
    interface IntrinsicElements {
        "tera-button": TeraButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tera-button": LocalJSX.TeraButton & JSXBase.HTMLAttributes<HTMLTeraButtonElement>;
        }
    }
}
